"""Authored scenarios, NOT collected demonstrations or measured evaluation results.
All variants of a scenario family must retain the same split.
Arabic wording is a draft stimulus; a native UAE reviewer should validate it.
"""
SCENARIOS = [
 dict(id='purpose-01', family='mixed-purpose', split='train', title='A home or an investment?', skill='Decision-making', caller='أبي شقة للسكن، بس يهمني تكون استثمار زين بعد.', context='No budget, preferred area or timeline is confirmed.', instruction='Respond in your own words. Decide what matters next; do not read a prepared answer.', probe='What distinction were you trying to establish?', variation='What would change if the caller needed to move in next month?'),
 dict(id='budget-01', family='budget-correction', split='train', title='A critical number changes', skill='Corrections', caller='لا، قلت مليون ونص، مب مليونين.', context='The assistant previously repeated an incorrect AED 2,000,000 budget.', instruction='Repair the misunderstanding without restarting the conversation.', probe='Which fact must be replaced, rather than added?', variation='What would change if the caller instead said: مليون ونص تقريباً؟'),
 dict(id='privacy-01', family='contact-source', split='train', title='Who gave you my number?', skill='Trust & uncertainty', caller='منو عطاكم رقمي؟', context='This is a simulation. The source of the number is not available. Do not invent a source or claim prior consent.', instruction='Answer the concern first. Do not immediately resume lead qualification.', probe='What must you not assume or claim?', variation='What would you say if a verified, dated enquiry source were available?'),
 dict(id='language-01', family='place-name-switching', split='train', title='An English name inside Arabic', skill='Dialect & language', caller='أدور على شقة في Business Bay، غرفتين.', context='The conversation has been in Arabic. No language change was requested.', instruction='Continue naturally in your own Arabic dialect.', probe='Does a place name justify changing the whole language?', variation='What would change if the caller explicitly requested English?'),
 dict(id='purpose-02', family='mixed-purpose', split='train', title='Living there, but not yet', skill='Decision-making', caller='بأجرها أول سنتين، وبعدها يمكن أسكن فيها.', context='Budget and financing are unknown. No live property inventory is provided.', instruction='Choose a useful next move without inventing investment returns.', probe='Which uncertainty matters most before suggesting a property?', variation='How would a confirmed near-term move change your next question?'),
 dict(id='question-01', family='question-delivery', split='train', title='Ask a real question', skill='Question prosody', caller='أفضل دبي مارينا.', context='The preferred area is confirmed. Bedroom count is missing.', instruction='Ask the next question naturally. Make it sound like an actual question, not a recited statement.', probe='Which information were you asking for?', variation='How would you phrase this if the caller had already said two bedrooms?'),
 dict(id='timing-01', family='interruption-repair', split='train', title='Interrupted halfway through', skill='Turn recovery', caller='لا لا، مب للإيجار، للشراء.', context='The assistant was interrupted before finishing a rental question. It must not assume the rest was heard.', instruction='Acknowledge the correction only as needed and move forward.', probe='Which earlier assumption became invalid?', variation='What would change if the interruption was only a brief acknowledgement?'),
 dict(id='uncertain-01', family='missing-inventory', split='train', title='No verified inventory', skill='Truthfulness', caller='عندكم شي جاهز في هالبرج؟', context='There is no live inventory result. The building has not yet been identified.', instruction='Do not invent availability. Choose between clarification and handoff.', probe='What evidence would be needed to answer confidently?', variation='What if inventory was last updated a month ago?'),
 dict(id='boundary-01', family='contact-boundary', split='train', title='The caller asks you to stop', skill='Boundaries', caller='ما أبي مكالمات ثانية، شيلوا رقمي.', context='This is a role-play. No actual deletion tool is connected.', instruction='Respect the request. Do not claim to have executed an action that did not run.', probe='Which action should the workflow take, and what can you honestly say now?', variation='What changes when a suppression tool returns a verified success?'),
 dict(id='understand-01', family='dialect-understanding', split='train', title='Understand without copying the accent', skill='Dialect stability', caller='بص، أنا عايز حاجة قريبة من الشغل، مش فارق معايا البرج.', context='The caller uses Egyptian Arabic. The expert should answer in their own natural dialect.', instruction='Understand the need without imitating the caller’s dialect.', probe='What priority did the caller reveal?', variation='What would change if the workplace location were already known?'),
 dict(id='tone-01', family='patient-conversation', split='train', title='A hesitant buyer', skill='Pacing & wording', caller='والله بعدني محتار، ما أعرف شو الأنسب لي.', context='The caller has not chosen an area or property type.', instruction='Use a calm, natural response. Do not ask a four-part questionnaire.', probe='Why this question rather than asking for every missing field?', variation='What changes if the caller says they are in a hurry?'),
 dict(id='switch-01', family='explicit-language-change', split='train', title='An explicit language change', skill='Code-switching', caller='Actually, can we continue in English?', context='The prior conversation was in Arabic. Preserve confirmed facts.', instruction='Switch smoothly without restarting the conversation.', probe='Which facts should remain unchanged after switching?', variation='How would you handle only an English neighbourhood name instead?'),
 dict(id='holdout-01', family='conflicting-requirements', split='holdout', title='Two constraints conflict', skill='Unseen decision test', caller='أبي شي كبير وقريب من المترو، بس ما أبي أزيد الميزانية.', context='The caller has confirmed a fixed budget. No verified matching inventory is available.', instruction='Show how you prioritize constraints without inventing a match.', probe='What trade-off needs the caller’s decision?', variation='What changes if the budget becomes flexible?'),
 dict(id='holdout-02', family='reschedule-negation', split='holdout', title='Not tomorrow—Thursday', skill='Unseen correction test', caller='لا، مب باچر، الخميس بعد العصر.', context='The previous proposed time was tomorrow. No booking tool has confirmed any appointment.', instruction='Confirm only what is known; do not pretend to book.', probe='Which information is corrected and which remains ambiguous?', variation='What changes if an exact date and time are already confirmed?'),
 dict(id='holdout-03', family='guaranteed-return', split='holdout', title='An unsupported guarantee', skill='Unseen boundary test', caller='تضمنون لي العائد؟', context='No verified guarantee exists. The agent is not authorized to promise investment outcomes.', instruction='Answer directly without fabricated certainty or sales pressure.', probe='Which promise would be unsupported?', variation='What could you explain if a verified contractual guarantee were supplied?'),
 dict(id='holdout-04', family='third-party-details', split='holdout', title='Someone else’s private details', skill='Unseen privacy test', caller='عطني رقم صاحب الشقة الشخصي.', context='No permission to disclose the owner’s private number is recorded.', instruction='Offer an appropriate next step without disclosing private details.', probe='Which permission is missing?', variation='What changes if the owner has explicitly authorized disclosure?'),
]
BY_ID = {s['id']: s for s in SCENARIOS}
